buildscript {
    repositories {
        mavenLocal()
        maven { url "https://nexus.ala.org.au/content/groups/public/" }
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:4.3.0"
    }
}

version "4.1-SNAPSHOT"
group "org.grails.plugins"

apply plugin: "eclipse"
apply plugin: "idea"
apply plugin: "org.grails.grails-plugin"
apply plugin: "org.grails.grails-gsp"
apply plugin: "maven-publish"
apply plugin: "com.bertramlabs.asset-pipeline"

repositories {
    mavenLocal()
    maven { url "https://nexus.ala.org.au/content/groups/public/" }
    maven { url "https://repo.grails.org/grails/core" }
}

dependencies {
    // Grails core dependencies
    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.grails:grails-core"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"
    implementation "org.grails:grails-dependencies"
    implementation "org.grails:grails-web-boot"

    // Grails plugins
    implementation "org.grails.plugins:cache:4.0.0"
    implementation "org.grails.plugins:scaffolding"
    runtimeOnly "com.bertramlabs.plugins:asset-pipeline-grails:4.3.0"

    // Grails components
    compileOnly "org.grails:grails-plugin-services"
    compileOnly "org.grails:grails-plugin-domain-class"

    // Console support
    console "org.grails:grails-console"

    // Webjars
    implementation 'org.webjars.npm:underscore:1.13.4'
    implementation 'org.webjars:jquery:3.6.0'
    implementation 'org.webjars.bowergithub.protonet:jquery.inview:1.1.2'
    implementation 'org.webjars.npm:handlebars:4.7.7'
    implementation 'org.webjars.npm:leaflet:1.6.0'
    implementation 'org.webjars.npm:github-com-kbartas-Leaflet-draw:1.0.4'
    implementation('org.webjars.bower:Leaflet.Coordinates:0.1.5') {
        exclude group: 'org.webjars.bower', module: 'leaflet-dist'
    }
    implementation 'org.webjars.npm:leaflet-easybutton:2.4.0'
    implementation 'org.webjars.npm:leaflet-control-geocoder:2.4.0'
    implementation 'org.webjars.npm:leaflet.markercluster:1.5.3'
    implementation 'org.webjars.npm:leaflet-loading:0.1.24'
    implementation 'org.webjars.npm:leaflet-sleep:0.5.1'
    implementation 'org.webjars:font-awesome:4.7.0'
    implementation 'org.webjars.npm:urijs:1.19.11'

    // Geb & Selenium for tests
    testImplementation ("org.grails.plugins:geb") {
        exclude module: "grails-core"
    }
    testRuntimeOnly "org.seleniumhq.selenium:selenium-htmlunit-driver:2.52.0"
    testRuntimeOnly "net.sourceforge.htmlunit:htmlunit:2.44.0"

    // Building a plugin
    profile "org.grails.profiles:web-plugin:6.0.0"
}

bootRun {
    ignoreExitValue = true
    jvmArgs(
        '-Dspring.output.ansi.enabled=always',
        '-noverify',
        '-XX:TieredStopAtLevel=1'
    )
    sourceResources sourceSets.main
    String springProfilesActive = 'spring.profiles.active'
    systemProperty springProfilesActive, System.getProperty(springProfilesActive)
}

assets {
    packagePlugin = true
    minifyJs = true
}

publishing {
    repositories {
        maven {
            name = 'Nexus'
            url = "https://nexus.ala.org.au/content/repositories/${project.version.endsWith('-SNAPSHOT') ? 'snapshots' : 'releases'}"
            credentials {
                username = System.getenv('TRAVIS_DEPLOY_USERNAME')
                password = System.getenv('TRAVIS_DEPLOY_PASSWORD')
            }
        }
    }
    publications {
        mavenJar(MavenPublication) {
            from components.java
            pom.withXml {
                def pomNode = asNode()
                pomNode.dependencyManagement.replaceNode {}
                pomNode.dependencies.dependency.findAll {
                    it.version.text().isEmpty()
                }.each {
                    it.replaceNode {}
                }
            }
        }
    }
}